### ISSUE TITLE
Use AccuWeather API for Forecast Channel (When that is finished and released in a update)

### ISSUE THREAD

**Issue by Selvenity** [Ascript89/onliine#2]
The [AccuWeather API](https://developer.accuweather.com/) could help with giving accurate weather for when the Forecast Channel is to be developed, as giving forecasts is what the channel is for, and a API from a Weather Service could help with making sure you don't have to spend HOURS changing the weather for every place in the world.

**Comment by jerosajose** [comment]
I'd have to make sure it's completely free, but it's a great suggestion.

**Comment by Selvenity** [comment]
> I'd have to make sure it's completely free, but it's a great suggestion.

it is, you gotta include some info like your phone number and first and last name and stuff like that when signing up
