### ISSUE TITLE
idea, and problem in readme

### ISSUE THREAD

**Issue by ADev531** [Ascript89/onliine#5]
hi,
i found dolphin emu is not possible (possible but 1 frame per seconds, need to change almost all code)
instead, an installer to install wii emu and onliine call that.
then, wii emu will run.

**Comment by jerosajose** [comment]
I'm sorry if I should have understood your message correctly, but I didn't lol.

Could you please mention what do you mean from the ReadMe? Just for clarity.

**Comment by ADev531** [comment]
dolphin emu in webassembly is not possible, need to make from scratch..

**Comment by jerosajose** [comment]
Oh yeah, about that. That idea has already been scrapped by votations on the Discord server poll that I made back in October iirc.

I'd have also discarded it as it's pretty hard lol, but it was an interesting concept.
